/*
 * This source file was generated by the Gradle 'init' task
 */
package com.bouanani;

import com.bouanani.classes.Cat;
import java.lang.reflect.*;
public class App {

    public static void main(String[] args) throws Exception {

        Cat myCat = new Cat("cat1" , 12);
        Field[] catField = myCat.getClass().getDeclaredFields();

        for(Field f : catField){
            if(f.getName().equals("name")){
                f.setAccessible(true);
                f.set(myCat,"catty");
            }
        }

        Method[] catMethods = myCat.getClass().getDeclaredMethods();
        for(Method m : catMethods){
          if(m.getName().equals("meow")){
              m.setAccessible(true);
              m.invoke(myCat);
          }
            //System.out.println(m.getName());
        }
        //System.out.println(myCat.getName());
    }
}
