/*
 * This source file was generated by the Gradle 'init' task
 */
package com.bouanani;

import com.bouanani.classes.Cat;

public class App {

    public static void main(String[] args) {

        Cat myCat = new Cat("cat1" , 12);

    }
}
